export const START_RECEIVED_LOOP = 'app/receive/START_RECEIVED_LOOP'
export const STOP_RECEIVED_LOOP = 'app/receive/STOP_RECEIVED_LOOP'
export const ACQUIRE_RECEIVED_MESSAGES = 'app/receive/ACQUIRE_RECEIVED_MESSAGES'
export const ACQUIRE_RECEIVED_MESSAGES_SUCCESS = 'app/receive/ACQUIRE_RECEIVED_MESSAGES_SUCCESS'
export const TOGGLE_MESSAGE = 'app/receive/TOGGLE_MESSAGE'


export default {
  START_RECEIVED_LOOP,
  STOP_RECEIVED_LOOP,
  ACQUIRE_RECEIVED_MESSAGES,
  ACQUIRE_RECEIVED_MESSAGES_SUCCESS,
  TOGGLE_MESSAGE,
};
