/* ACTION TYPE CONSTANTS
 * You can use any convention you wish here, but the name should remain UPPER_SNAKE_CASE for consistency.
 */

export const START_SEND_ACTION = 'app/send/START_SEND_ACTION'
export const SEND_ALREADY_STARTED = "app/send/SEND_ALREADY_STARTED"
export const AFTER_START_SEND_ACTION = 'app/send/AFTER_START_SEND_ACTION'
export const STOP_SEND_ACTION = 'app/send/STOP_SEND_ACTION'
export const SELECT_MESSAGE_LIST_ACTION = "app/send/SELECT_MESSAGE_LIST_ACTION"
export const SELECT_MESSAGE_ACTION = "app/send/SELECT_MESSAGE_ACTION"
export const FOCUS_ON_MESSAGE_ACTION = "app/send/FOCUS_ON_MESSAGE_ACTION"

export default {
  START_SEND_ACTION,
  AFTER_START_SEND_ACTION,
  SEND_ALREADY_STARTED,
  STOP_SEND_ACTION,
  SELECT_MESSAGE_ACTION,
  SELECT_MESSAGE_LIST_ACTION,
  FOCUS_ON_MESSAGE_ACTION
};
